{
  "hash": "d04ff204cbacf6c3eeb26b58d6a35bf3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"UMAIR BIN SAAD\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**    \n- Apply spatial operations to answer policy-relevant research questions    \n- Integrate census demographic data with spatial analysis   \n- Create publication-quality visualizations and maps     \n- Work with spatial data from multiple sources    \n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nMy analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n#Analysis Steps\n\nI have Completed the following analysis, tried to give the brief explanations about each step (Although if you want codes you may check technical details through my source code on GitHub:\n\n#Step 1: Data Detail\n\nI have used the following data :  \n- Pennsylvania county boundaries  \n- Pennsylvania hospitals     \n- Pennsylvania census tracts     \n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nI will answer the following questions in my analysis :  \n- How many hospitals are in your dataset?   \n- How many census tracts?   \n- What coordinate reference system is each dataset in?    \n\n---\n\n#I am obtaining tract-level demographic data for Pennsylvania from American Census Survey data portal.   \n\nFollowing are the variables I am taking into consideration   \n- Total population   \n- Median household income   \n- Population 65 years and over (you may need to sum multiple age categories)   \n\n\n::: {.cell}\n\n:::\n\n\n**Questions to answer:**\n\n- What year of ACS data are you using?  \nI am using 2022 ACS data.\n\n- How many tracts have missing income data?  \nThere is 0 tract with missing income data.\n\n- What is the median income across all PA census tracts?  \nMedian income across all PA census tracts = 70188\n\n::: {.cell}\n\n:::\n\n\nVulnerable Populations:     \nI have classified those people as vulnerable whose income is less than 50000 and whom age is above 65 years of age in all tracts of Pensylvania.\n\nThese two are my criteria:    \n1. Low median household income (median_incomeE < 50000)    \n2. Significant elderly population (Population_65_over > 200)  \n\n\n\n::: {.cell}\n\n:::\n\n\n#### My replies to some important questions related to my analysis:\n\n- What income threshold did you choose and why?   \nI have chosen an income threshold of $50,000 because it is a common benchmark for low-income status in many policy analyses. It also allows us to capture a significant portion of the population that may be struggling financially, while still including enough tracts for meaningful analysis.\n- What elderly population threshold did you choose and why?   \nI have chosen an elderly population threshold of 200 because it represents a significant number of elderly residents in a tract, which may indicate a higher need for healthcare services. This threshold allows us to focus on tracts that have a substantial elderly population, which is often more vulnerable to health issues and may require more frequent access to hospitals.\n- How many tracts meet your vulnerability criteria?    \nThere are total 555 tracts that meet the vulnerability criteria of having a median household income below $50,000 and an elderly population of over 200.\n- What percentage of PA census tracts are considered vulnerable by your definition?     \nTotal 16.1103 percent of PA census tracts are considered vulnerable by the defined criteria. That are basically 555 tracts out of total 3447 tracts in Pennsylvania. Simply 555/3447*100 = 16.1103 percent.\n\n\n::: {.cell}\n\n:::\n\n\n---\n\n#### Distance calculation to Hospitals \n\nI calculated the distance to the nearest hospital from each vulnerable tract.\n\n**Your Task:**\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n#### My replies to some important points:\n\n- Use an appropriate projected coordinate system for Pennsylvania    \n  I have used the PROJCRS[\"NAD83 / UTM zone 17N\"] (EPSG:26917) which is a common projected coordinate system for the eastern United States, including Pennsylvania. It uses meters as units, which allows for accurate distance calculations.\n  \n- Calculate distances in miles    \n  Distance has been calculated in mile (1 Mile = 1609.34 Meters)  \n  \n- Explain why you chose your projection    \n  I have chosen this projection because it is a common projected coordinate system for the eastern United States, including Pennsylvania. It uses meters as units, which allows for accurate distance calculations.\n\n**Questions to answer:**\n\n::: {.cell}\n\n:::\n\n- What is the average distance to the nearest hospital for vulnerable tracts?     \n  The average distance to the nearest hospital for vulnerable tracts is approximately 2.619415 miles.   \n  \n\n::: {.cell}\n\n:::\n\n- What is the maximum distance?     \n  The maximum distance to the nearest hospital for vulnerable tracts is approximately 18.96458 miles.    \n  \n- How many vulnerable tracts are more than 15 miles from the nearest hospital?    \nThere are total 128 vulnerable tracts that are more than 15 miles from the nearest hospital.    \n\n::: {.cell}\n\n:::\n\n  \n\n#### Identification of Underserved Areas    \n\nI Defined \"underserved\" as :    \nvulnerable tracts that are more than 15 miles from the nearest hospital are considered underserved because they likely face significant barriers to accessing healthcare services, which can lead to worse health outcomes. This distance can be a major obstacle for individuals who may not have reliable transportation or who have mobility issues, particularly among the elderly population. Identifying these underserved areas is crucial for targeting healthcare investments and policy interventions to improve access and equity in healthcare services.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n## Primary results:  \n- How many tracts are underserved?    \nThere are total 9 tracts that are underserved, meaning they are vulnerable and located more than 15 miles from the nearest hospital.\n- What percentage of vulnerable tracts are underserved?    \nApproximately 1.62% of vulnerable tracts are underserved, meaning they are located more than 15 miles from the nearest hospital. This is calculated by dividing the number of underserved tracts (9) by the total number of vulnerable tracts (555) and multiplying by 100. \n\n::: {.cell}\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n- Does this surprise you? Why or why not?    \nIt is somewhat surprising that only a small percentage of vulnerable tracts are underserved, given the significant barriers to healthcare access that can exist in rural and low-income areas. However, it may also reflect the fact that many vulnerable populations are located in more urban or suburban areas where hospitals are more accessible. It highlights the importance of looking beyond just the number of vulnerable tracts and considering the geographic distribution and specific needs of these populations when planning healthcare investments and interventions.\n\n---\n\n## Aggregate to County Level:   \nI used spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n\n#### county-level statistics:   \nThe number of vulnerable tracts in each county is calculated by performing a spatial join between the vulnerable tracts and the county boundaries, and then counting the number of vulnerable tracts that fall within each county. This will gave us a count of how many vulnerable tracts are located in each county, which can help identify which counties have the highest concentration of vulnerable populations that may be underserved in terms of healthcare access. Philadelphia County has the highest number of vulnerable tracts, with a total of 138 vulnerable tracts. This indicates that Philadelphia County has a significant concentration of vulnerable populations that may be at risk of being underserved in terms of healthcare access, particularly if many of these tracts are located far from hospitals. Allegheny County has the second highest number of vulnerable tracts, with a total of 80 vulnerable tracts. This suggests that Allegheny County also has a significant concentration of vulnerable populations that may require targeted healthcare investments and policy interventions to improve access to healthcare services. Luzerne County has the third highest number of vulnerable tracts, with a total of 29 vulnerable tracts. This indicates that Luzerne County also has a notable concentration of vulnerable populations that may be at risk of being underserved in terms of healthcare access. These findings highlight the importance of focusing healthcare investments and policy interventions in these counties to address the needs of vulnerable populations and improve healthcare access and equity.   \n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: The number of vulnerable tracts in each county\n\n|Name of Counties | number of vulnerable tracts|\n|:----------------|---------------------------:|\n|Adams County     |                           1|\n|Allegheny County |                          80|\n|Armstrong County |                           2|\n|Beaver County    |                          12|\n|Bedford County   |                           2|\n|Berks County     |                          11|\n|Blair County     |                           8|\n|Bradford County  |                           1|\n\n\n:::\n:::\n\n\n#### Number of underserved tracts:  \nThe number of underserved tracts in each county is calculated by performing a spatial join between the underserved tracts (vulnerable tracts that are more than 15 miles from the nearest hospital) and the county boundaries, and then counting the number of underserved tracts that fall within each county. This will give us a count of how many underserved tracts are located in each county, which can help identify which counties have the highest concentration of vulnerable populations that may be at risk of being underserved in terms of healthcare access. Clearfield County has the highest number of underserved tracts, with a total of 3 underserved tracts. This indicates that Pike County has a significant concentration of vulnerable populations that are located far from hospitals and may be at risk of being underserved in terms of healthcare access. Forest County has the second highest number of underserved tracts, with a total of 2 underserved tracts. This suggests that Chester County also has a notable concentration of vulnerable populations that are located far from hospitals and may require targeted healthcare investments and policy interventions to improve access to healthcare services. \t\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: The number of vulnerable tracts in each county that are more than 15 Miles away from county\n\n|Name of Counties  | number of vulnerable tracts|\n|:-----------------|---------------------------:|\n|Cameron County    |                           1|\n|Centre County     |                           1|\n|Clearfield County |                           3|\n|Forest County     |                           2|\n|Juniata County    |                           1|\n|Monroe County     |                           1|\n\n\n:::\n:::\n\n- Percentage of vulnerable tracts that are underserved\n# Calculate percentage of vulnerable tracts that are underserved\n\nApproximately 0.02% of vulnerable tracts are underserved, meaning they are located more than 15 miles from the nearest hospital. This is calculated by dividing the number of underserved tracts (9) by the total number of vulnerable tracts (555) and multiplying by 100. \n\n\n::: {.cell}\n\n:::\n\n\n- Average distance to nearest hospital for vulnerable tracts\nThe average distance to the nearest hospital for vulnerable tracts is approximately 2.619415 miles. This is calculated by taking the mean of the dist_to_nearest variable for all vulnerable tracts, which represents the distance from each tract centroid to the nearest hospital.\n\n\n::: {.cell}\n\n:::\n\n\n- Total vulnerable population    \n  The total vulnerable population is calculated by summing the total_popE variable for all vulnerable tracts. This gives us an estimate of the total number of 1861909 people living in vulnerable tracts, which can help us understand the scale of the population that is at risk of being vulnerable in terms of healthcare access.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: The total vulnerable population\n\n| Total vulnerable population|\n|---------------------------:|\n|                   1,861,909|\n\n\n:::\n:::\n\n\n\n#### Questions to some important questions\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\nThe 5 counties with the highest percentage of underserved vulnerable tracts are Clearfield County, Forest County, Cameron County, \t\nCentre County and Juniata County(Although these counties have same percentage i-e Cameron County, Centre County and Juniata County). These counties have the highest proportion of vulnerable tracts that are located more than 15 miles from the nearest hospital, indicating that they may be at greater risk of being underserved in terms of healthcare access. Targeting healthcare investments and policy interventions in these counties could help improve access to healthcare services for vulnerable populations and address disparities in healthcare access and outcomes.\n\n- Which counties have the most vulnerable people living far from hospitals?\n  the counties with the most vulnerable people living far from hospitals are Clearfield County, Forest County, Cameron County, Monroe County. These counties have the highest number of vulnerable tracts that are located more than 15 miles (i-e 18+) from the nearest hospital, indicating that they may have a significant population of vulnerable individuals who are at risk of being underserved in terms of healthcare access. Focusing healthcare investments and policy interventions in these counties could help improve access to healthcare services for vulnerable populations and address disparities in healthcare access and outcomes.\n  \n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: The counties with the most vulnerable people living far from hospitals\n\n|Name of Counties  | Distance In Miles|Geometry                 |\n|:-----------------|-----------------:|:------------------------|\n|Clearfield County |          18.96458|POINT (715707.5 4544151) |\n|Cameron County    |          18.67476|POINT (730638.3 4599085) |\n|Forest County     |          18.67159|POINT (658732.6 4596293) |\n|Forest County     |          18.12447|POINT (636569.4 4598061) |\n|Monroe County     |          17.72684|POINT (964425 4566910)   |\n|Clearfield County |          17.29383|POINT (714544.4 4555896) |\n|Clearfield County |          17.06501|POINT (710938.5 4524946) |\n|Juniata County    |          15.91816|POINT (785524.7 4476807) |\n|Centre County     |          15.21372|POINT (734566.2 4530652) |\n|Crawford County   |          14.51497|POINT (544432.5 4606561) |\n\n\n:::\n:::\n\n---\n\n#### I am Creating Summary Table \n\n\n\n**Your Task:**\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Details about the counties with the most vulnerable people living far from hospitals\n\n|Name Counties     | Distance to nearest hospital (Mile| Total Estimated population| Median Income of People| Population that is above 65 years of age|Geometry of the tracts   |\n|:-----------------|----------------------------------:|--------------------------:|-----------------------:|----------------------------------------:|:------------------------|\n|Clearfield County |                           18.96458|                      3,012|                  44,756|                                      489|POINT (715707.5 4544151) |\n|Cameron County    |                           18.67476|                      1,988|                  34,387|                                      428|POINT (730638.3 4599085) |\n|Forest County     |                           18.67159|                      4,258|                  44,324|                                      791|POINT (658732.6 4596293) |\n|Forest County     |                           18.12447|                      2,701|                  47,132|                                      802|POINT (636569.4 4598061) |\n|Monroe County     |                           17.72684|                      1,299|                  44,105|                                      314|POINT (964425 4566910)   |\n|Clearfield County |                           17.29383|                      3,343|                  49,659|                                      987|POINT (714544.4 4555896) |\n|Clearfield County |                           17.06501|                      2,376|                  48,345|                                      495|POINT (710938.5 4524946) |\n|Juniata County    |                           15.91816|                      1,782|                  48,958|                                      492|POINT (785524.7 4476807) |\n|Centre County     |                           15.21372|                      3,327|                  46,951|                                      547|POINT (734566.2 4530652) |\n|Crawford County   |                           14.51497|                      1,306|                  49,342|                                      479|POINT (544432.5 4606561) |\n\n\n:::\n:::\n\n\n\n\n## I have made Comprehensive Visualization \nI have created a choropleth map showing healthcare access challenges at the county level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n\ncoords_matrix <- st_coordinates(underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles)\nView(coords_matrix)\nunderserved_tracts_out_of_vulnerable_which_are_more_than_15_miles <- cbind(underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles, coords_matrix[, c(\"X\", \"Y\")])\nView(underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles)\n#underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles <- rename(underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles, Tracts_namess = NAMELSAD)\nView(underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles)\nst_crs(underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:26917 \n  wkt:\nPROJCRS[\"NAD83 / UTM zone 17N\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"UTM zone 17N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",-81,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"North America - between 84°W and 78°W - onshore and offshore. Canada - Nunavut; Ontario; Quebec. United States (USA) - Florida; Georgia; Kentucky; Maryland; Michigan; New York; North Carolina; Ohio; Pennsylvania; South Carolina; Tennessee; Virginia; West Virginia.\"],\n        BBOX[23.81,-84,84,-78]],\n    ID[\"EPSG\",26917]]\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals_coords_matrix <- st_coordinates(hospitals)\nView(hospitals_coords_matrix)\nhospitals <- cbind(hospitals, hospitals_coords_matrix[, c(\"X\", \"Y\")])\nhospitals <- st_transform(hospitals, crs = 26917)\nView(hospitals)\nst_crs(hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:26917 \n  wkt:\nPROJCRS[\"NAD83 / UTM zone 17N\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"UTM zone 17N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",-81,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"North America - between 84°W and 78°W - onshore and offshore. Canada - Nunavut; Ontario; Quebec. United States (USA) - Florida; Georgia; Kentucky; Maryland; Michigan; New York; North Carolina; Ohio; Pennsylvania; South Carolina; Tennessee; Virginia; West Virginia.\"],\n        BBOX[23.81,-84,84,-78]],\n    ID[\"EPSG\",26917]]\n```\n\n\n:::\n\n```{.r .cell-code}\nunderserved_tracts_out_of_vulnerable_which_are_more_than_15_miles = rename(underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles, any_of(c(\"new\" = \"XPZ\")))\nView(underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles)\n\n\n\n\n#ggplot(data = underserved_tracts_out_of_vulnerable_which_are_more_than_15_miles, aes(x= X,  y=Y, colour = new))+ geom_point(size = 5) + geom_point(data = hospitals, \n             #aes(x = X, y = Y), # Map the aesthetics for the new data\n          #   color = \"red\",     # Set a specific color for the second data set, outside aes()\n          #   size = 2)+ \n  #labs(title = \"County-Level Choropleth Map of Underserved Vulnerable Tracts in Pennsylvania\",\n   #    subtitle = \"Red points indicate hospital locations\",\n     #  caption = \"Data Source: ACS 2022, Pennsylvania Department of Health\") + \n         # theme_void()   \n```\n:::\n\n\nI have done this:  \n- Filled counties by percentage of vulnerable tracts that are underserved   \n- Included hospital locations as points   \n- Used an appropriate color scheme \n- Included clear title, subtitle, and caption    \n- Used theme_void()    \n- Added a legend with formatted labels    \n\n---\n\n### Here below is the detailed Vulnerability Map \nI created a map highlighting underserved vulnerable tracts.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:26917 \n  wkt:\nPROJCRS[\"NAD83 / UTM zone 17N\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"UTM zone 17N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",-81,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"North America - between 84°W and 78°W - onshore and offshore. Canada - Nunavut; Ontario; Quebec. United States (USA) - Florida; Georgia; Kentucky; Maryland; Michigan; New York; North Carolina; Ohio; Pennsylvania; South Carolina; Tennessee; Virginia; West Virginia.\"],\n        BBOX[23.81,-84,84,-78]],\n    ID[\"EPSG\",26917]]\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:26917 \n  wkt:\nPROJCRS[\"NAD83 / UTM zone 17N\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"UTM zone 17N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",-81,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"North America - between 84°W and 78°W - onshore and offshore. Canada - Nunavut; Ontario; Quebec. United States (USA) - Florida; Georgia; Kentucky; Maryland; Michigan; New York; North Carolina; Ohio; Pennsylvania; South Carolina; Tennessee; Virginia; West Virginia.\"],\n        BBOX[23.81,-84,84,-78]],\n    ID[\"EPSG\",26917]]\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:26917 \n  wkt:\nPROJCRS[\"NAD83 / UTM zone 17N\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"UTM zone 17N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",-81,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"North America - between 84°W and 78°W - onshore and offshore. Canada - Nunavut; Ontario; Quebec. United States (USA) - Florida; Georgia; Kentucky; Maryland; Michigan; New York; North Carolina; Ohio; Pennsylvania; South Carolina; Tennessee; Virginia; West Virginia.\"],\n        BBOX[23.81,-84,84,-78]],\n    ID[\"EPSG\",26917]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nI have done this in the above picture: \n- Showed underserved vulnerable tracts in a contrasting color\n- Included county boundaries for context\n- Showed hospital locations\n- Used appropriate visual hierarchy \n- Included informative title and subtitle\n\n---\n\n## I carried a Distribution Analysis:\nCreated a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n\n- I generated a histogram or density plot of distances:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n- I generated a Box plot comparing distances across regions\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\n\n- I generated a Bar chart of underserved tracts by county\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\nThe chart above shows the distribution of distances to hospitals for vulnerable populations in Pennsylvania. The bar chart indicates that the some of vulnerable tracts are not located within a few miles of the nearest hospital, with a long tail extending to higher distances. This suggests that while many vulnerable populations have relatively good access to healthcare services, there are some tracts that face significant barriers due to their distance from hospitals. Targeted interventions may be needed to improve healthcare access for those living in more remote areas.\n\n\n\nI showed in graphs:  \n- Clear axes labels with units  \n- Appropriate title  \n- Professional formatting  \n- Brief interpretation  \n\n---\n\n\n# My Own Data Analysis \n\nI have chosen to do the analysis on \"Green Space Equity\" in Philadelphia. I will be using the data of parks, street trees and census tracts.  \n#### Environmental Justice\n\n## Green Space Equity \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\nFirst of all for this analysis, I will be using the data of parks, street trees and census tracts. I will be using the data of Philadelphia city. I will be using the data of 2022 ACS for census tracts. I will be using the data of parks and street trees from OpenDataPhilly. I have gotten data from get_acs function for census tracts. I have also read the data of parks and street trees using st_read function. I have transformed the data of parks and street trees to the same projection as census tracts. I have also calculated the coordinates of parks and street trees using st_coordinates function. I have also calculated the median income and median population.\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |=====                                                                 |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |==========                                                            |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |============                                                          |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |==============                                                        |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |================                                                      |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |=====================                                                 |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |=======================                                               |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |=========================                                             |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |===========================                                           |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |======================================                                |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |=================================================                     |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |===================================================                   |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |========================================================              |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n:::\n\n\nI transformed the data of Philadelphia census tracts to the same projection as parks and street trees, which is NAD83 / UTM zone 17N (EPSG:26917). This projection is appropriate for spatial analysis in Philadelphia because it uses meters as units, allowing for accurate distance calculations and spatial operations. By ensuring that all datasets are in the same projected coordinate system, I can perform spatial joins, buffering, and other analyses without issues related to misaligned geometries or inaccurate distance measurements.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PPR_Program_Sites' from data source \n  `C:\\Users\\Umair Bin Saad\\Desktop\\Green Space Equity\\parks\\PPR_Program_Sites.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 171 features and 10 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.2563 ymin: 39.90444 xmax: -74.96944 ymax: 40.12284\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PPR_Program_Sites' from data source \n  `C:\\Users\\Umair Bin Saad\\Desktop\\Green Space Equity\\parks\\PPR_Program_Sites.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 171 features and 10 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8377493 ymin: 4852065 xmax: -8345560 ymax: 4883810\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:26917 \n  wkt:\nPROJCRS[\"NAD83 / UTM zone 17N\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"UTM zone 17N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",-81,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"North America - between 84°W and 78°W - onshore and offshore. Canada - Nunavut; Ontario; Quebec. United States (USA) - Florida; Georgia; Kentucky; Maryland; Michigan; New York; North Carolina; Ohio; Pennsylvania; South Carolina; Tennessee; Virginia; West Virginia.\"],\n        BBOX[23.81,-84,84,-78]],\n    ID[\"EPSG\",26917]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-27-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ppr_tree_inventory_2025' from data source \n  `C:\\Users\\Umair Bin Saad\\Desktop\\Green Space Equity\\Street Trees\\ppr_tree_inventory_2025.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 151726 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -8380434 ymin: 4847791 xmax: -8344373 ymax: 4885938\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:26917 \n  wkt:\nPROJCRS[\"NAD83 / UTM zone 17N\",\n    BASEGEOGCRS[\"NAD83\",\n        DATUM[\"North American Datum 1983\",\n            ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4269]],\n    CONVERSION[\"UTM zone 17N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",-81,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"North America - between 84°W and 78°W - onshore and offshore. Canada - Nunavut; Ontario; Quebec. United States (USA) - Florida; Georgia; Kentucky; Maryland; Michigan; New York; North Carolina; Ohio; Pennsylvania; South Carolina; Tennessee; Virginia; West Virginia.\"],\n        BBOX[23.81,-84,84,-78]],\n    ID[\"EPSG\",26917]]\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58514\n```\n\n\n:::\n:::\n\n## Median Income:\nMedian Income of Philadelphia is $58514. So, I will consider the tracts with median income less than $40,000 as low-income tracts because it is significantly below the median income of Philadelphia, indicating that these tracts may have a higher concentration of low-income residents who could be at greater risk of lacking access to green spaces and other resources. This threshold allows us to focus on areas that are likely to face more significant challenges in terms of environmental justice and access to green space.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 887\n```\n\n\n:::\n:::\n\n## Median number of white people:\nMedian number of whiteE people of Philadelphia is 887. So, I will consider the tracts with whiteE population less than 200 as minority neighborhoods because these tracts have a significantly lower number of white residents compared to the median, indicating that they may have a higher concentration of minority populations who could be at greater risk of lacking access to green spaces and other resources. This threshold allows us to focus on areas that are likely to face more significant challenges in terms of environmental justice and access to green space for minority communities.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 894.5\n```\n\n\n:::\n:::\n\n## Median number of black people:\nMedian number of blackE people of Philadelphia is 895. So, I will consider the tracts with blackE population less than 210 as minority neighborhoods because these tracts have a significantly lower number of black residents compared to the median, indicating that they may have a higher concentration of minority populations who could be at greater risk of lacking access to green spaces and other resources. This threshold allows us to focus on areas that are likely to face more significant challenges in terms of environmental justice and access to green space for minority communities.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 129.5\n```\n\n\n:::\n:::\n\n## Median number of asian people\"\nMedian number of asianE people of Philadelphia is 130. So, I will consider the tracts with asianE population less than 50 as minority neighborhoods because these tracts have a significantly lower number of Asian residents compared to the median, indicating that they may have a higher concentration of minority populations who could be at greater risk of lacking access to green spaces and other resources. This threshold allows us to focus on areas that are likely to face more significant challenges in terms of environmental justice and access to green space for minority communities.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 231\n```\n\n\n:::\n:::\n\n## Median number of hispanic people\"\nMedian number of hispanicE people of Philadelphia is 231. So, I will consider the tracts with hispanicE population less than 10 as minority neighborhoods because these tracts have a significantly lower number of Hispanic residents compared to the median, indicating that they may have a higher concentration of minority populations who could be at greater risk of lacking access to green spaces and other resources. This threshold allows us to focus on areas that are likely to face more significant challenges in terms of environmental justice and access to green space for minority communities.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n## Median number of Native_Hawaiian people:\nMedian number of Native_HawaiianE people of Philadelphia is 0. So, I will consider the tracts with Native_HawaiianE population less than 10 as minority neighborhoods because these tracts have a significantly lower number of Native Hawaiian residents compared to the median, indicating that they may have a higher concentration of minority populations who could be at greater risk of lacking access to green spaces and other resources. This threshold allows us to focus on areas that are likely to face more significant challenges in terms of environmental justice and access to green space for minority communities.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n## Median number of American_Indian people:\n#Median number of American_IndianE people of Philadelphia is 0. So, I will consider the tracts with American_IndianE  population less than 10 as minority neighborhoods because these tracts have a significantly lower number of American Indian residents compared to the median, indicating that they may have a higher concentration of minority populations who could be at greater risk of lacking access to green spaces and other resources. This threshold allows us to focus on areas that are likely to face more significant challenges in terms of environmental justice and access to green space for minority communities.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n## Median number of otherE people:\nMedian number of otherE people of Philadelphia is 0. So, I will consider the tracts with otherE population less than 10 as minority neighborhoods because these tracts have a significantly lower number of residents categorized as \"other\" compared to the median, indicating that they may have a higher concentration of minority populations who could be at greater risk of lacking access to green spaces and other resources This threshold allows us to focus on areas that are likely to face more significant challenges in terms of environmental justice and access to green space for minority communities. \n\n\n\n\n# vulnerable tracts based on our criteria:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlow_income_Philidelphia_data <- filter(Philidelphia_data, median_incomeE < 40000 & whiteE < 200 | blackE < 210 & asianE > 0 | asianE < 50 & asianE > 0 | hispanicE < 10 & hispanicE > 0 | Native_HawaiianE < 10 & Native_HawaiianE > 0 | American_IndianE < 10 & American_IndianE > 0 | otherE < 10 & otherE > 0)\nView(low_income_Philidelphia_data)\nggplot() +\n  geom_sf(data = Philidelphia_data, fill = \"yellow\", color = \"grey\") +\n  geom_sf(data = low_income_Philidelphia_data, fill = \"red\", color = \"grey\")\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n\nI have filtered the Philadelphia census tracts to identify low-income and minority neighborhoods based on the defined criteria. The resulting dataset, low_income_Philidelphia_data, contains the 184 tracts out of 408 tracts that meet the criteria for being considered low-income and/or minority neighborhoods. These tracts are likely to face greater challenges in terms of access to green spaces and other resources, making them important areas of focus for environmental justice and urban planning efforts in Philadelphia.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\nThen I showed parks on the map. The parks are shown in dark green color. The low-income and minority neighborhoods are shown in red color, while the other tracts are shown in yellow color. This map allows us to visually assess the distribution of parks in relation to low-income and minority neighborhoods in Philadelphia, which can help identify areas that may be underserved in terms of access to green spaces and inform targeted interventions to improve environmental justice and urban planning efforts.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nThe blue points on the map represent the locations of street trees in Philadelphia. By overlaying the street tree data with the census tracts and park locations, we can visually assess the distribution of green spaces and tree canopy in relation to low-income and minority neighborhoods. This can help identify areas that may be underserved in terms of access to green spaces and inform targeted interventions to improve environmental justice and urban planning efforts in Philadelphia.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuffer_area_parks <- st_buffer(parks_shapefile, dist = 804.672) # 0.5 miles in meters\n###ggplot() +\n###  geom_sf(data = buffer_area_parks, fill = \"yellow\", color = \"grey\")\n###View(buffer_area_parks)\n```\n:::\n\n\nBut in analysis we are not taking trees as these are not suitalbe for analysis rather we are taking parks as these are more suitable for analysis. I have created a buffer of 0.5 miles (10-minute walk) around the parks to represent the area of influence of each park. This buffer allows us to visually assess which census tracts fall within a reasonable walking distance to the parks, which can help identify areas that may have better access to green spaces and those that may be underserved in terms of park access. By overlaying the buffer areas with the low-income and minority neighborhoods, we can further analyze the equity of access to green spaces in Philadelphia.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\nyou can see the pink areas on the map represent the buffer zones around the parks, indicating the areas that are within a 10-minute walk (0.5 miles) of the parks. By visually assessing the overlap between these buffer zones and the low-income and minority neighborhoods (shown in red), we can identify which neighborhoods have better access to parks and which may be underserved in terms of green space access. This analysis can help inform targeted interventions to improve environmental justice and urban planning efforts in Philadelphia.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n st_agr(buffer_area_parks) = \"constant\"\n st_agr(low_income_Philidelphia_data) = \"constant\"\noverlaps_buffer_area_parks_with_vulnerable_tracts <- st_intersection(buffer_area_parks, low_income_Philidelphia_data)\n\n\nggplot() +\n  geom_sf(data = Philidelphia_data, fill = \"yellow\", color = \"grey\") +\n  geom_sf(data = low_income_Philidelphia_data, fill = \"red\", color = \"grey\") +\n    # 3. Add the points on top\n  geom_sf(data = parks_shapefile, color = \"darkGreen\", size = 2) +\n  geom_sf(data = overlaps_buffer_area_parks_with_vulnerable_tracts, fill = \"blue\", color = \"grey\", alpha = 0.7)+\n  labs(title = \"Map of Park Access in Philadelphia\",\n       subtitle = \"Blue areas represent low-income and minority\n  neighborhoods within a 10-minute walk of parks\",\n       caption = \"Data Source: ACS 2022, OpenDataPhilly\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nThe purple areas on the map represent the low-income and minority neighborhoods that fall within the buffer zones around the parks, indicating that these neighborhoods have better access to green spaces. While red areas represent low-income and minority neighborhoods that do not fall within the buffer zones, indicating that they may be underserved in terms of park access. This analysis helps us understand the spatial distribution of park access in relation to vulnerable populations in Philadelphia and can inform targeted interventions to improve environmental justice and urban planning efforts in the city.\"\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoints_in_polygons <- st_join(street_trees, Philidelphia_data, left = FALSE)\nView(points_in_polygons)\n\nNumber_of_trees_in_each_tracts <-  points_in_polygons %>% count(NAME)\n\nNumber_of_trees_in_each_tracts <- sf::st_drop_geometry(Number_of_trees_in_each_tracts)\nView(Number_of_trees_in_each_tracts)    \n\nPhilidelphia_data_plus_Number_of_trees_in_each_tracts <- left_join(Philidelphia_data, Number_of_trees_in_each_tracts, by = \"NAME\")\nView(Philidelphia_data_plus_Number_of_trees_in_each_tracts)    \n\n\nPer_capita_tree_canopy <- Philidelphia_data_plus_Number_of_trees_in_each_tracts %>%\n  mutate(tree_canopy_per_capita = n / total_popE)\n\n\nrrrrr <-  select(Per_capita_tree_canopy, NAME, total_popE, n, tree_canopy_per_capita) \nView(rrrrr)\n\nkable(head(rrrrr, n = 10),\n    col.names = c(\"NAME\"=\"Census_Tracts\", \"total_popE\" = \"Total population\", \"n\"= \"Number_of_trees \", \"tree_canopy_per_capita\" = \"Number_of_trees(canopy)_per_capita\", \"geometry\"= \"Geometry \" ),\n    caption = \"Tree/Tree canopy for each tract per capita \",\n    format.args = list(big.mark = \",\"),\n    )\n```\n\n::: {.cell-output-display}\n\n\nTable: Tree/Tree canopy for each tract per capita \n\n|Census_Tracts                                         | Total population| Number_of_trees | Number_of_trees(canopy)_per_capita|Geometry                       |\n|:-----------------------------------------------------|----------------:|----------------:|----------------------------------:|:------------------------------|\n|Census Tract 15; Philadelphia County; Pennsylvania    |            3,251|              586|                          0.1802522|MULTIPOLYGON (((998585.9 44... |\n|Census Tract 18; Philadelphia County; Pennsylvania    |            3,300|              514|                          0.1557576|MULTIPOLYGON (((998552.9 44... |\n|Census Tract 28.02; Philadelphia County; Pennsylvania |            5,720|              617|                          0.1078671|MULTIPOLYGON (((998558.6 44... |\n|Census Tract 40.01; Philadelphia County; Pennsylvania |            4,029|              347|                          0.0861256|MULTIPOLYGON (((998355 4435... |\n|Census Tract 63; Philadelphia County; Pennsylvania    |            4,415|              137|                          0.0310306|MULTIPOLYGON (((991814.8 44... |\n|Census Tract 77; Philadelphia County; Pennsylvania    |            1,815|              545|                          0.3002755|MULTIPOLYGON (((994498.6 44... |\n|Census Tract 87.01; Philadelphia County; Pennsylvania |            3,374|              408|                          0.1209247|MULTIPOLYGON (((994507.1 44... |\n|Census Tract 110; Philadelphia County; Pennsylvania   |            2,729|              335|                          0.1227556|MULTIPOLYGON (((994243.9 44... |\n|Census Tract 115; Philadelphia County; Pennsylvania   |            4,881|              399|                          0.0817455|MULTIPOLYGON (((990613.7 44... |\n|Census Tract 140; Philadelphia County; Pennsylvania   |            5,753|              414|                          0.0719625|MULTIPOLYGON (((998228.6 44... |\n\n\n:::\n:::\n\n\n\nOther than our main analysis we also did small spatial and statistical analysis to calculate tree canopy availability per capita across census tracts in Philadelphia. First, a spatial join (st_join) is conducted between the street tree point dataset and the Philadelphia census tract polygon dataset, ensuring that only trees located within tract boundaries are retained . This operation assigns each individual tree to the census tract in which it geographically falls. Next, the joined dataset is grouped by tract name and the number of trees in each tract is counted using the count() function, producing a summary table of total trees per census tract. The geometry column is then removed using st_drop_geometry() so that the data can be handled as a standard tabular dataframe for non-spatial processing. After this, the tree count data are merged back into the original census tract dataset using a left_join based on the tract name, ensuring that each tract polygon now contains both its demographic attributes (including total population) and the corresponding number of trees. Finally, a new variable, tree_canopy_per_capita, is calculated by dividing the number of trees in each tract by the total population estimate (total_popE). This produces a standardized per capita measure of tree availability, allowing for meaningful comparison of urban greenery distribution across census tracts regardless of population size. And then we used Kable function to show the first 10 rows of the data.\nResults shows that Census Tract 369.01; Philadelphia County; Pennsylvania has the highest number of per capita trees and that are 8.48 in number. while Census Tract 9809.05; Philadelphia County; Pennsylvania has the least number of per capita trees. \"\n\n\n\nData Sources used in above analysis are:\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\"\n\n\nAnswers to some important Questions :\n- What dataset did you choose and why?\nWe used Green Space Equity related data sets which include Street Trees, parks & Census tracts (race/income demographics)\n- What is the data source and date?\nOpenDataPhilly:** https://opendataphilly.org/datasets/ \nStreet Trees, parks = 2025 while Census tracts (race/income demographics) =2022\n- What CRS is it in? Did you need to transform it?\nYes transformed it to NAD83 / UTM zone 17N\" EPSG:26917.\n\n\n\n\nresearch statement:\n\nMy research analysis answers the low income and vulnerable minorities access to parks in each tract of the Philadelphia. \n\nI used all these spatial analysis along with other spatial analysis too.\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n\n\n\n## Finally - A few comments about your incorporation of feedback!\nYes I have incorporated suggestions which were given to me by teached specially the code hiding in my document.\n\n\n\n",
    "supporting": [
      "lab2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}